<?php

namespace App\Http\Requests\Roles;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class CreateRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        $tableName = config('permission.table_names');
        return [
            'name' => ['required','string','between:2,60','unique:' . $tableName['roles'],],
            'guard_name' => ['required','string','between:2,60', Rule::in(['api','admin'])],
        ];
    }

    /**
     * @return array
     */
    public function attributes()
    {
        // TODO: Change the autogenerated stub
        return [
            'name' => __('message.role.name'),
            'guard_name' => __('message.permission.guard_name'),
        ];
    }
}
